FitBitToStravaApp/Pages/ClearCache.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FitBitToStravaApp.Pages
{
    public class ClearCacheModel : PageModel
    {
        public LinkGenerator LinkGenerator { get; }

        

        public ClearCacheModel(LinkGenerator linkGenerator)
        {
            LinkGenerator = linkGenerator;
        }


        public void OnGet()
        {
        }
    }
}

FitBitToStravaApp/Pages/Error.cshtml.cs
using DataObjects.Tools;
using Fitbit.Api.Portable;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace FitBitToStravaApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    [AllowAnonymous]
    public class ErrorModel : PageModel
    {
        public string ErrorCode { get; set; }
        public string App { get; set; }
        public string Message { get; set; }


        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

            // Get the exception details
            var exceptionFeature = HttpContext.Features.Get<IExceptionHandlerPathFeature>();
            var exception = exceptionFeature?.Error;
            if (exception is FitbitRateLimitException)
            {
                this.App = ApplicationType.Fitbit;
                this.Message = exception.Message;
            }
            else
            {
                this.ErrorCode = Request.Query["code"];
                this.App = Request.Query["app"];
                _logger.LogError(exception, "Unhandled error");
            }
        }
    }

}

FitBitToStravaApp/Pages/Index.cshtml.cs
using DataBase.Repository;
using DataObjects.Activities;
using Fitbit.Api.Portable;
using FitbitSDK.Transformer;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services;
using StravaSDK;

namespace FitBitToStravaApp.Pages
{
    [Authorize()]
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IExcerciseRepository excerciseRepository;
        private readonly MigrateActivityService _migrateActivityService;
        private readonly CheckUploadStatusService _checkUploadStatusService;
        private DateTime checkDate = DateTime.Now.AddDays(1);
        public DateTime LastCheckedDate { 
            get { return this.checkDate; } set { this.checkDate = value; } }
        public bool IsFitbitAuthenticated {
            get
            {
                string val = HttpContext.Session.GetString(nameof(IsFitbitAuthenticated));
                bool isFitbitAuthenticated = false;
                bool.TryParse(val, out isFitbitAuthenticated);
                return isFitbitAuthenticated;
            }
            set {
                HttpContext.Session.SetString(nameof(IsFitbitAuthenticated), value.ToString());
            }
        }

        public List<BaseActivity> Activities { get; private set; } = new List<BaseActivity>();

        private IFitbitClient _fitbitClient;

        public IndexModel(ILogger<IndexModel> logger, IFitbitClient fitbitClient, IExcerciseRepository excerciseRepository, 
            MigrateActivityService migrateActivityService, CheckUploadStatusService checkUploadStatusService)
        {
            _fitbitClient = fitbitClient;
            _logger = logger;
            this.excerciseRepository = excerciseRepository;
            _migrateActivityService = migrateActivityService;
            _checkUploadStatusService = checkUploadStatusService;
        }

        public async Task OnGet()
        {
            if (string.IsNullOrWhiteSpace(User.GetFitbitToken()))
            {
                Redirect("/Privacy");
            }

            var date = DateTime.Now;

            if (Request.Query.ContainsKey("date"))
            {
                DateTime.TryParseExact(Request.Query["date"], "yyyyMMdd", null, System.Globalization.DateTimeStyles.None, out date);
            }
            LastCheckedDate = date;

            var activities = (await _fitbitClient.GetActivityLogsListAsync(LastCheckedDate))?.Activities?? new List<Fitbit.Api.Portable.Models.Activities>();
            foreach (var item in activities)
            {
                this.Activities.Add(await FitbitToDataObjects.RetrieveActivityAsync(item, User.GetFitbitToken()));
            }
            var migrated = this.excerciseRepository.GetByIds(this.Activities.Select(c => c.ActivityId).ToArray()).ToList();
            foreach (var activity in migrated)
            {
                var item = Activities.First(c => c.ActivityId == activity.ExcerciseId);
                item.Migrated = true;
                item.UploadStatus = activity.StravaUploadStatus;
                item.UploadId = activity.StravaUploadId;
                item.MigrationError = activity.StravaUploadError;
                item.StravaActivityId = activity.StravaId;
            }

        }

        public async Task<IActionResult> OnPostMigrateAsync(long id, [FromQuery] DateTime date, [FromQuery] ActivityType? migrationActivityType)
        {

            await _migrateActivityService.ExecuteAsync(id, date, User.GetFitbitToken(), User.GetUserId(), migrationActivityType);
            return RedirectToPage(new {date= date.ToString("yyyyMMdd") });
        }



        public async Task<IActionResult> OnPostRefreshAsync(long id, [FromQuery] DateTime date)
        {
            await _checkUploadStatusService.ExecuteAsync(id, date, User.GetUserId(), User.GetFitbitToken());
            return RedirectToPage(new { date = date.ToString("yyyyMMdd") });
        }


    }
}

FitBitToStravaApp/Pages/Logout.cshtml.cs
using Fitbit.Api.Portable;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;

namespace FitBitToStravaApp.Pages
{
    public class LogoutModel : PageModel
    {
        private IConfiguration _configuration;

        public LogoutModel(IConfiguration configuration)
        {
            this._configuration = configuration;
        }
        public async Task<IActionResult> OnGet()
        {
            var fitbitToken = User.GetFitbitToken();
            var stravaToken = User.GetStravaToken();
            // Sign out of the default authentication scheme (e.g., Cookies)
            // Clear the session
            HttpContext.Session.Clear();

            // Sign out
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            if (!string.IsNullOrWhiteSpace(fitbitToken))
            {
                await RevokeFitbitToken(fitbitToken);
            }

            if (HttpContext.Request.Cookies.ContainsKey(".AspNetCore.Cookies"))
            {
                HttpContext.Response.Cookies.Delete(".AspNetCore.Cookies");
            }
            HttpContext.User = new System.Security.Claims.ClaimsPrincipal();
            Response.Headers.Remove("Cache-Control");
            Response.Headers.Remove("Pragma");
            Response.Headers.Append("Cache-Control", "no-store, no-cache, must-revalidate, post-check=0, pre-check=0");
            Response.Headers.Append("Pragma", "no-cache");
            // Redirect to the home page or any other desired page
            return RedirectToPage("/ClearCache");
        }

        public async Task RevokeFitbitToken(string accessToken)
        {
            var stravaConfig = _configuration.GetSection("Authentication:Fitbit");
            var clientId = stravaConfig["ClientId"];
            var clientSecret = stravaConfig["ClientSecret"];

            using var client = new HttpClient();
            var request = new HttpRequestMessage(HttpMethod.Post, "https://api.fitbit.com/oauth2/revoke");
            request.Content = new FormUrlEncodedContent(new[]
            {
        new KeyValuePair<string, string>("token", accessToken)
    });
            request.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Basic",
                Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes($"{clientId}:{clientSecret}")));

            var response = await client.SendAsync(request);
            if (!response.IsSuccessStatusCode)
            {
                // Handle revocation failure
            }
        }
    }
}

FitBitToStravaApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FitBitToStravaApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

FitBitToStravaApp/Pages/ClearCache.cshtml
@page
@model FitBitToStravaApp.Pages.ClearCacheModel
@{
    var homePage = Model.LinkGenerator.GetPathByPage("/Index");
}
<h1>This page will redirect shortly...</h1>
<script>

    deleteAllCookies();

     setTimeout(() => {
        window.location.href = "@homePage";
    }, 3000);

    function deleteAllCookies() {
        console.log("deleting cookies..");
        const cookies = document.cookie.split(";");

        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i];
            const eqPos = cookie.indexOf("=");
            const name = eqPos > -1 ? cookie.substr(0, eqPos) : cookie;
            document.cookie = name + "=;expires=Thu, 01 Jan 1970 00:00:00 GMT";
        }
    }
</script> 

FitBitToStravaApp/Pages/Index.cshtml
@page

@using DataObjects.Tools
@using Microsoft.AspNetCore.Authentication
@using DataObjects.Activities;

@model IndexModel
@{
    ViewData["Title"] = "Home page";
    var formattedDate = Model.LastCheckedDate.ToString("yyyy-MM-dd");
}

@section Scripts {

    <script>


        var changeFromDateObject = function (selectedDate) {
             // Format the selected date to "yyyyMMdd"
            const formattedDate = $.datepicker.formatDate("yymmdd", selectedDate);

            // Get the base page URL from a data attribute
            const pageUrl = $(".datepicker").data("page-url");

            // Construct the final URL with the query parameter
            const url = `${pageUrl}?date=${formattedDate}`;

            // Navigate to the generated URL
            window.location.href = url;
        };

        var changeDate = function (selectedDate) {
             // Format the selected date to "yyyyMMdd"
            changeFromDateObject($.datepicker.parseDate("yy-mm-dd", selectedDate));
        };

        $(document).ready(function () {
            $('.datepicker').datepicker({
                dateFormat: "yy-mm-dd",
                onSelect: function (selectedDate) {
                    changeDate(selectedDate);
                }
            });
             // Set the initial value of the datepicker from the server
            var initialDate = $(".datepicker").data("initial-date");
            if (initialDate) {
                $(".datepicker").datepicker("setDate", initialDate);
            }

            $("[name='previousDay']").click(function() {
                var dateStr = $(".datepicker").val();
                var selectedDate = $.datepicker.parseDate("yy-mm-dd", dateStr);
                selectedDate.setDate(selectedDate.getDate() - 1);
                changeFromDateObject(selectedDate);
            });

            $("[name='nextDay']").click(function() {
                var dateStr = $(".datepicker").val();
                var selectedDate = $.datepicker.parseDate("yy-mm-dd", dateStr);
                selectedDate.setDate(selectedDate.getDate() + 1);
                changeFromDateObject(selectedDate);
            });

            $(".custom-activity-type").change(function() {
                var activityId = $(this).data("activityid");
                var relatedSubmit = $("#submit-"+ activityId)
                var selectedValue = $(this).val();
                
                const params = relatedSubmit.attr("formaction").split('&'); 
                var formAction = "";
                for (var i = 0; i< params.length; i++){
                    var currentParam = params[i];
                    if (currentParam.startsWith("migrationActivityType")) {
                        currentParam = "migrationActivityType=" + selectedValue;
                    }
                    var unionChar = (i == params.length - 1) ? "" : "&";
                    formAction += (currentParam + unionChar);
                }
                relatedSubmit.attr("formaction", formAction);
            });
        });
    </script>
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>

    
    <div class="row d-flex justify-content-center">
        <div class="col col-2 col-md-1">
            <button type="button" name="previousDay" class="btn btn-outline-dark" data-toggle="tooltip" data-placement="top" aria-label="Previous day" title="Previous day">
                <i class="bi bi-caret-left-square" aria-hidden="true"></i>

            </button>
        </div>
        <div class="form-group col col-6 col-md-2">
            <div class="input-group date" data-provide="datepicker">
                <input type="text" name="datepicker" data-initial-date="@formattedDate" class="datepicker form-control" aria-label="Selected date" data-page-url="@Url.Page("/Index")">
                <span class="input-group-text" id="basic-addon2"><i class="bi bi-calendar"></i></span>
            </div>
        </div>
        <div class="col col-2 col-md-1">
            <button type="button" name="nextDay" class="btn btn-outline-dark" data-toggle="tooltip" data-placement="top" aria-label="Next day" title="Next day">
                <i class="bi bi-caret-right-square" aria-hidden="true"></i>

            </button>

        </div>
    </div>
    <form method="post">
    <table class="table">
        <thead>
            <tr>
                    <th class="d-none d-lg-table-cell" scope="col">#</th>
                    <th class="d-none d-md-table-cell d-lg-table-cell" scope="col">Date</th>
                    <th scope="col">Activity</th>
                    <th scope="col">Type</th>
                    <th scope="col">Upload Status</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var item in Model.Activities)
                {
                    <tr>
                            <th class="d-none  d-lg-table-cell" scope="row">@item.ActivityId</th>
                            <td class="d-none d-md-table-cell d-lg-table-cell">@item.StartDate</td>
                            <td>@item.Name </td>
                            <td>

                                @if (!item.Migrated && item.ActivityType == ActivityType.Treadmill &&  await this.HttpContext.AuthenticateAsync(ApplicationType.Strava) is { Succeeded: true })
                                {

                                    <select class="custom-activity-type" name="@($"customActivityType-{item.ActivityId}")" data-activityId = "@item.ActivityId">
                                        <option value="@ActivityType.Treadmill" selected="selected">Treadmill</option>
                                        <option value="@ActivityType.Walk">Walk</option>
                                        <option value="@ActivityType.Run">Run</option>
                                    </select>
                                } else if (!item.Migrated && (item.ActivityType == ActivityType.Elliptic || item.ActivityType == ActivityType.Spinning) &&  await this.HttpContext.AuthenticateAsync(ApplicationType.Strava) is { Succeeded: true })
                                {

                                    <select class="custom-activity-type" name="@($"customActivityType-{item.ActivityId}")" data-activityId = "@item.ActivityId">
                                        <option value="@ActivityType.Elliptic" selected="selected">Elliptical</option>
                                        <option value="@ActivityType.Bicycle">Bicycle</option>
                                        <option value="@ActivityType.VirtualRide">Stationary Bike</option>
                                    </select>
                                } else {
                                    @item.ActivityType.ToString()
                                }
                                / @item.DistanceKm.ToString("F2") Km
                            </td>
                            <td>
                                @item.UploadStatus                                
                            </td>
                            <td>
                                @if (!item.Migrated && await this.HttpContext.AuthenticateAsync(ApplicationType.Strava) is { Succeeded: true })
                                {

                                    <button type="submit" class="btn btn-outline-primary" asp-page-handler="Migrate" id="@($"submit-{item.ActivityId}")"
                                            asp-route-id="@item.ActivityId" 
                                            asp-route-date="@Model.LastCheckedDate"
                                            asp-route-migrationActivityType="@item.ActivityType"
                                            data-toggle="tooltip" data-placement="top" title="Migrate">
                                        <i class="bi bi-cloud-upload" data-toggle="tooltip" data-placement="top" title="Migrate" aria-hidden="true"></i>
                                    </button>
                                }
                                @if (item.Migrated && !item.StravaError)
                                {

                                    @if (@item.StravaActivityId != null)
                                    {
                                        <a target="_blank" href='@($"https://www.strava.com/activities/" + item.StravaActivityId)'>Watch in Strava</a>
                                    }
                                    else
                                    {
                                        <i class="bi bi-check-lg text-success" data-toggle="tooltip" data-placement="top" title="Migrated" aria-label="Migrated"></i>
                                    }
                                }
                                @if (item.StravaError)
                                {
                                    <i class="bi bi-exclamation-triangle text-danger-emphasis" data-toggle="tooltip" data-placement="top" title="@item.MigrationError" data-html="true" aria-label="Migration error"></i>
                                }

                                @if (item.IsProcessing)
                                {
                                    <button class="btn btn-outline-primary" type="submit" asp-page-handler="Refresh" asp-route-id="@item.ActivityId" asp-route-date="@Model.LastCheckedDate"
                                            data-toggle="tooltip" data-placement="top" title="Check Status">
                                        <i class="bi bi-arrow-clockwise" aria-hidden="true"></i>
                                    </button>
                                }

                                
                            </td>
                            
                    </tr>
                }

            }
        </tbody>
    </table>
    </form>
    
    
</div>

FitBitToStravaApp/Pages/Logout.cshtml
@page
@model FitBitToStravaApp.Pages.LogoutModel
@{
}
<p>Logging you out...</p>